### ISSUE TITLE
missing .vsixmanifest file

### ISSUE THREAD

**Issue by ghost** [wfpaisa/plane-vscode#1]
Hi, 

I don't know if this repo is still active or not but since you've updated your gtk3 theme I thought... why not ?
So I tried to install it several times but the theme won't appear if the plane folder don't have a .vsixmanifest file.
There are also an issue in your repo cause you've uploaded a symbolic link (https://github.com/wfpaisa/plane-vscode/blob/master/plane-vscode) and I'm not sure it's relevant
Finally the bootstrap script looks into ~/.vscode/ folder but (in some distro. Arch, at least) vscode stores themes in ~/.vscode-oss/. I don't know if there's a way to find the right "path"

Thank you for your fantastic work !

**Comment by wfpaisa** [comment]
Hi prooff, thanks for your revision, I check the link, and the `vsixmanifest` file no is necessary yet, you can install this theme just download the repository and put in your extensions .vscode folder.
![s1](https://user-images.githubusercontent.com/1735752/75163998-1f90a600-56ee-11ea-94de-286339927b50.png)
![s2](https://user-images.githubusercontent.com/1735752/75164003-20c1d300-56ee-11ea-9d8b-8f5364910c60.png)

**Comment by wfpaisa** [comment]
one thing more, remember to reload the window after put  the theme

**Comment by ghost** [comment]
Ok you were right. I forgot to try to restart the application...
Thank you for your time !
